---
# yamllint
#
# TAG should be defined by caller.  Used to ensure testing containers have
# unique but known names.
version: '3'

volumes:
  pip:
    driver: local

services:
  postgres:
    image: postgres:12
    ports:
      - "5434:5432"
    container_name: postgres-$TAG
    environment:
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - type: bind
        source: ../tests/instance
        target: /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -h localhost -p 5432 -U postgres -d postgres
