#!/bin/sh

export PYTHONPATH=.

# inspection testing
tests/inspection/intest pylint yamllint shellcheck || exit 1

# unit tests
pytest -v --cov=medial --cov-report=html --cov-report=term tests/ || exit 1
